export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_CATEGORIES: "SET_CATEGORIES",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  };

